language: python
python:
  - 3.6
services:
  - postgresql
addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.4
install:
  - pip install pipenv
  - PIPENV_IGNORE_VIRTUALENVS=1 pipenv install --dev
before_script:
  - psql -c 'create database test_gwsw;' -U postgres
  - psql -U postgres -c "create extension postgis" test_gwsw
  - psql -U postgres test_gwsw < hydxlib/tests/threedi_database_schema/work_empty_schema_2018-12-21.sql
script:
  - pipenv run pytest
after_success:
  - pipenv run coveralls

deploy:
  provider: pypi
  user: "nens"
  password:
    secure: hoRLQrJm1Y5Na0d0xEGH267t6x9cQBJzPuLCsfmze02qz5fShVbJmB61cJS+FpC3NnKmi+5TiTEJ1Tz1pmtSKWLGLXgjzFk0rjBwkvH7h3QK4brPl4kPpZ/y/GK5bjQ5K3olmP6b+P/P5QhAolB8Rkfyt130RdAuIqPIrxFu18c+OOf/+fh2vCrN544xVH2js+xJmpPzfWkHaFZlxSH6kPbYNJGByg+QG7r0Gzx7WumREkD5IZFL0ICTKvUitS2QVfuK8KlvrqjIULv0+086U7D2FdZLnwuN6Zte8pV2q6UoskWhNZ9U72+I9drBidYOB1JGv8OpB3hIij4MN14vGBQ4MlnXsjTpKHH0Gjv9muKia9kPxhZw/Ml8NvDAo6/5gxVSjsisBqSlJBEh7bAEABbcI+JuyPbeCBKBkqJ4K+CNXgc8LRddz8mq4UA59gM4PONMMlSS8sdYwzgZ7Cu8JrAy0E2jLbFwW1EQFLH9CFTNsP5T6Qo4NnxsmuXt9sJOoE9oABeyPkbCY2CZRAUZj2TmS4VYE9Oz/N26nd+dZANDJDvc+ncx0QXT7xTqSkJDLce31cKTJMtQYz1DeDNuUwo/PHpEYf8Tgcafhakf/1DsH9Ah2kI1Q0AljWSCVRAvbonBnd0eKUjW5vqmU9j8FUZBr4xQj0L/T/PDvc4fdqM=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
